cli:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

build:
  - changed-files:
      - any-glob-to-any-file:
          - "docker/**"
          - "package.json"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
          - "docs/**"

server:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "__tests__/**"

web:
  - changed-files:
      - any-glob-to-any-file:
          - "public/**"

config:
  - changed-files:
      - any-glob-to-any-file:
          - ".env"
          - "tsconfig.json"
          - ".prettierrc.json"
