version: "3.8"

services:
  docker-staticmaps:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx # Specify the Dockerfile in the subdirectory
    image: mxdcodes/docker-staticmaps:latest
    container_name: docker-staticmaps
    restart: always
    ports:
      - "80:80"
      - "3000:3000"
    environment:
      - API_KEY=${API_KEY}
