name: "Auto-label CI/CD Changes"

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write


jobs:
  label-ci:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.repo.full_name == 'dietrichmax/docker-staticmaps'
    steps:
      - name: Apply Labels
        uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6
        with:
          configuration-path: .github/labeler.yml
          sync-labels: false
          dot: false
