name: Update Release Draft

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  autolabel:
    name: Label pull request
    if: github.event_name == 'pull_request_target' && github.event.pull_request.base.repo.full_name == 'dietrichmax/docker-staticmaps'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Apply labels
        uses: release-drafter/release-drafter/autolabeler@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7
        with:
          config-name: release-drafter.yml

  update_release_draft:
    name: Update release draft
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Update Release Draft
        uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
